# Generated by Django 2.2.12 on 2020-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200421_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('artist', 'Artist'), ('organiser', 'Organiser'), ('band', 'Band')], max_length=500),
        ),
    ]
