# Generated by Django 2.2.2 on 2020-04-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_auto_20200421_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='about',
            new_name='about_text',
        ),
        migrations.AddField(
            model_name='user',
            name='about_link',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Not specified', max_length=20),
        ),
    ]
