# Generated by Django 2.2.2 on 2020-04-29 18:39

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_remove_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
