# Generated by Django 2.2.2 on 2020-05-06 19:39

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_event_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=2500)),
                ('video', embed_video.fields.EmbedVideoField(default='')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_user', to='userlogin.User')),
            ],
        ),
    ]
