# Generated by Django 2.2.12 on 2020-06-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0009_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.TextField(choices=[('artist', 'Artist'), ('organiser', 'Organiser'), ('band', 'Band'), ('custom user', 'Custom User')], default='artist', max_length=500),
        ),
    ]
