# Generated by Django 2.2.12 on 2020-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0010_auto_20200603_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.ManyToManyField(to='userlogin.User'),
        ),
    ]
