# Generated by Django 2.2.12 on 2020-06-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0012_auto_20200603_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='performer',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_event', to='userlogin.Event'),
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_accepted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_event', to='userlogin.Event')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='userlogin.User')),
            ],
        ),
    ]
