# Generated by Django 2.2.12 on 2020-06-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0013_auto_20200604_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
