# Generated by Django 2.2.12 on 2020-06-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0014_performer_responded'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True)),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post2', to='userlogin.Post')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer2', to='userlogin.User')),
            ],
        ),
        migrations.CreateModel(
            name='RatedEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event1', to='userlogin.Event')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer1', to='userlogin.User')),
            ],
        ),
    ]
