# Generated by Django 2.2.12 on 2020-06-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0015_ratedevents_ratedpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatedEvents',
        ),
    ]
