# Generated by Django 2.2.12 on 2020-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0016_delete_ratedevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
